---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff --fix
        language: system
        types:
          - python
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types:
          - python
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types:
          - python
